GET https://localhost:4300/api/compromissos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YTlhOWFlMi0zZjMxLTQzOTMtZTcxOS0wOGRjZWUwNDIwODkiLCJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoidGVzdGUiLCJnaXZlbl9uYW1lIjoiSnVuaW5obyBUZXN0ZXMiLCJuYmYiOjE3Mjk3MDM5NDMsImV4cCI6MTczMDEzNTk0MywiaWF0IjoxNzI5NzAzOTQzLCJpc3MiOiJlQWdlbmRhIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdCJ9.KtZJkAIKD4QZzTCu2RBLV_0K3LTzg3kpid-KrV60veM
